### ISSUE TITLE
common lexicons?

### ISSUE THREAD

**Issue by snchknn** [snchknn/botlikh-mp-2020#7]
do we really need multiple lexd files? we obviously have to insert same lexicons e.g. case markers in almost every one of our lexd files. and what is the initial purpose of splitting a vocabulary into several parts? i also forgot how do we hfst-ify every one of them and intersect them all with one twol and then check test pairs concurrently? i tried to sort it out playing with your abaza makefile but its syntax is still kind of a mess for my eyes.

**Comment by agricolamz** [comment]
I thought `cat *.lexd > full.lexd` should merge them together in one file. With the possible exception that all files should have an empty line at the end of the file (that is not default on Windows).

**Comment by nlhowell** [comment]
George Moroz - notifications@github.com wrote:
> @nlhowell?

I'll answer in reverse order, since I am a stack.

> With the possible exception that all files should have an empty line
> at the end of the file (that is not default on Windows).

Yes, all files should end with a blank line.

You can check in a few ways; one is using `tail -c1`
```
$ echo oranges > my-good-file    # echo prints a newline
$ echo -n oranges > my-bad-file  # echo -n does not
$ [[ -n "$(tail -c1 my-bad-file)" ]] && echo "no newline at eof"
no newline at eof
$
```

If they don't, you can add a blank line:
```
$ echo >> my-bad-file
$ [[ -n "$(tail -c1 my-bad-file)" ]] && echo "no newline at eof"
$ [[ -z "$(tail -c1 my-bad-file)" ]] && echo "now it's good"
```

(the `-n` and `-z` are to check if a string is non-empty or empty,
respectively)

> I thought `cat *.lexd > \tmp\full.lexd` should merge them together

This works, though forward slashes are preferred: `cat *.lexd >
/tmp/full.lexd`

If you want to handle non-newline-terminated files, you can do
something hokey:
```
$ for f in *.lexd; do cat "$f"; echo; done > /tmp/full.lexd
```

> in one file that can be used in `hfst`.

First `lexd full.lexd > full.att`, then you can convert with
`hfst-txt2fst`.

Does that cover things?

Cheers,
Nick
